-- 20260715000001_portal_karyawan_schema.sql

-- 1. Modifikasi tabel karyawan
ALTER TABLE public.karyawan
ADD COLUMN username text UNIQUE,
ADD COLUMN auth_user_id uuid REFERENCES auth.users(id);

-- 2. Modifikasi tabel absensi
ALTER TABLE public.absensi
ADD COLUMN waktu_absen timestamptz,
ADD COLUMN sumber text CHECK (sumber IN ('karyawan_self', 'admin'));

-- 3. Modifikasi constraint profiles
ALTER TABLE public.profiles DROP CONSTRAINT profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('admin', 'user', 'karyawan'));

-- 4. Buat tabel cuti_izin
CREATE TABLE public.cuti_izin (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    karyawan_id bigint NOT NULL REFERENCES public.karyawan(id) ON DELETE CASCADE,
    tanggal_mulai date NOT NULL,
    tanggal_selesai date NOT NULL,
    jenis text NOT NULL CHECK (jenis IN ('Cuti', 'Izin', 'Sakit')),
    alasan text,
    status text NOT NULL DEFAULT 'Menunggu' CHECK (status IN ('Menunggu', 'Disetujui', 'Ditolak')),
    catatan_admin text,
    approved_by uuid REFERENCES auth.users(id),
    approved_at timestamptz,
    inserted_at timestamptz DEFAULT now()
);

-- 5. Buat tabel kasbon
CREATE TABLE public.kasbon (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    karyawan_id bigint NOT NULL REFERENCES public.karyawan(id) ON DELETE CASCADE,
    jumlah numeric NOT NULL CHECK (jumlah > 0),
    jumlah_cicilan int NOT NULL CHECK (jumlah_cicilan > 0),
    cicilan_per_bulan numeric NOT NULL,
    sisa_cicilan int NOT NULL,
    alasan text,
    status text NOT NULL DEFAULT 'Menunggu' CHECK (status IN ('Menunggu', 'Disetujui', 'Lunas', 'Ditolak')),
    tanggal_pengajuan timestamptz DEFAULT now(),
    approved_by uuid REFERENCES auth.users(id),
    approved_at timestamptz,
    dipotong_dari_gaji_id bigint REFERENCES public.gaji(id)
);

-- 6. Buat tabel hari_libur
CREATE TABLE public.hari_libur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal date NOT NULL UNIQUE,
    keterangan text NOT NULL,
    inserted_at timestamptz DEFAULT now()
);

-- 7. Buat tabel pengumuman
CREATE TABLE public.pengumuman (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul text NOT NULL,
    isi text NOT NULL,
    dibuat_oleh uuid REFERENCES auth.users(id),
    created_at timestamptz DEFAULT now()
);

-- 8. Enable RLS untuk tabel-tabel baru
ALTER TABLE public.cuti_izin ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kasbon ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hari_libur ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengumuman ENABLE ROW LEVEL SECURITY;

-- 9. Kebijakan RLS (Policy)

-- Policy cuti_izin
CREATE POLICY "Admin bisa kelola semua cuti_izin" ON public.cuti_izin
FOR ALL USING (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

CREATE POLICY "Karyawan bisa melihat cuti_izin miliknya sendiri" ON public.cuti_izin
FOR SELECT USING (
    exists (select 1 from public.karyawan where auth_user_id = auth.uid() and id = cuti_izin.karyawan_id)
);

CREATE POLICY "Karyawan bisa mengajukan cuti_izin untuk dirinya sendiri" ON public.cuti_izin
FOR INSERT WITH CHECK (
    exists (select 1 from public.karyawan where auth_user_id = auth.uid() and id = cuti_izin.karyawan_id)
);

-- Policy kasbon
CREATE POLICY "Admin bisa kelola semua kasbon" ON public.kasbon
FOR ALL USING (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

CREATE POLICY "Karyawan bisa melihat kasbon miliknya sendiri" ON public.kasbon
FOR SELECT USING (
    exists (select 1 from public.karyawan where auth_user_id = auth.uid() and id = kasbon.karyawan_id)
);

CREATE POLICY "Karyawan bisa mengajukan kasbon untuk dirinya sendiri" ON public.kasbon
FOR INSERT WITH CHECK (
    exists (select 1 from public.karyawan where auth_user_id = auth.uid() and id = kasbon.karyawan_id)
);

-- Policy hari_libur
CREATE POLICY "Admin bisa kelola hari_libur" ON public.hari_libur
FOR ALL USING (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

CREATE POLICY "Semua user (termasuk karyawan) bisa melihat hari_libur" ON public.hari_libur
FOR SELECT USING (auth.role() = 'authenticated');

-- Policy pengumuman
CREATE POLICY "Admin bisa kelola pengumuman" ON public.pengumuman
FOR ALL USING (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

CREATE POLICY "Semua user (termasuk karyawan) bisa melihat pengumuman" ON public.pengumuman
FOR SELECT USING (auth.role() = 'authenticated');
