create table public.karyawan (
  id bigint generated by default as identity not null,
  inserted_at timestamp with time zone null default now(),
  nama text not null,
  bagian text null default ''::text,
  tipe_gaji text null default 'Borongan'::text,
  gaji_pokok numeric null default 0,
  constraint karyawan_pkey primary key (id)
) TABLESPACE pg_default;

create table public.absensi (
  id bigint generated by default as identity not null,
  inserted_at timestamp with time zone null default now(),
  tanggal date not null,
  karyawan_id bigint null,
  status text not null,
  constraint absensi_pkey primary key (id),
  constraint absensi_tanggal_karyawan_id_key unique (tanggal, karyawan_id),
  constraint absensi_karyawan_id_fkey foreign KEY (karyawan_id) references karyawan (id) on delete CASCADE,
  constraint absensi_status_check check (
    (
      status = any (
        array[
          'Hadir'::text,
          'Izin'::text,
          'Alpa'::text,
          'Libur'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table public.gaji (
  id bigint generated by default as identity not null,
  inserted_at timestamp with time zone null default now(),
  karyawan_id bigint null,
  periode_mulai date not null,
  periode_selesai date not null,
  insentif numeric null default 0,
  lembur numeric null default 0,
  potongan numeric null default 0,
  gaji_pokok numeric null default 0,
  tarif_internal_hotel_snapshot numeric null,
  ongkos_per_kg_snapshot numeric null,
  constraint gaji_pkey primary key (id),
  constraint gaji_karyawan_id_fkey foreign KEY (karyawan_id) references karyawan (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.profiles (
  id uuid not null,
  nama text not null,
  role text not null,
  created_at timestamp with time zone null default now(),
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE,
  constraint profiles_role_check check ((role = any (array['admin'::text, 'user'::text])))
) TABLESPACE pg_default;

-- RPC untuk referensi pola
CREATE OR REPLACE FUNCTION public.bayar_cicilan_utang(p_utang_id bigint, p_tanggal text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_utang record;
    v_new_sisa int;
    v_new_status text;
BEGIN
    SELECT * INTO v_utang FROM public.utang WHERE id = p_utang_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Utang dengan id % tidak ditemukan', p_utang_id;
    END IF;

    IF v_utang.sisa_bulan <= 0 THEN
        RAISE EXCEPTION 'Utang sudah lunas';
    END IF;

    v_new_sisa := v_utang.sisa_bulan - 1;
    IF v_new_sisa <= 0 THEN
        v_new_status := 'LUNAS';
    ELSE
        v_new_status := 'AKTIF';
    END IF;

    INSERT INTO public.biaya (kategori, nominal, lunas, tanggal)
    VALUES ('CICILAN UTANG', v_utang.cicilan, true, p_tanggal::date);

    UPDATE public.utang 
    SET sisa_bulan = v_new_sisa, 
        status = v_new_status 
    WHERE id = p_utang_id;

    RETURN json_build_object(
        'sisa_bulan', v_new_sisa,
        'status', v_new_status
    );
END;
$$;
