-- 006_linen_harga_pelanggan.sql

ALTER TABLE linen_pelanggan ADD COLUMN IF NOT EXISTS pelanggan_id BIGINT REFERENCES pelanggan(id) ON DELETE CASCADE;
ALTER TABLE linen_pelanggan ADD COLUMN IF NOT EXISTS linen_id BIGINT REFERENCES master_linen(id) ON DELETE CASCADE;
ALTER TABLE linen_pelanggan ADD COLUMN IF NOT EXISTS urutan INTEGER NOT NULL DEFAULT 0;

ALTER TABLE harga_pelanggan ADD COLUMN IF NOT EXISTS pelanggan_id BIGINT REFERENCES pelanggan(id) ON DELETE CASCADE;
ALTER TABLE harga_pelanggan ADD COLUMN IF NOT EXISTS linen_id BIGINT REFERENCES master_linen(id) ON DELETE CASCADE;
ALTER TABLE harga_pelanggan ADD COLUMN IF NOT EXISTS harga NUMERIC NOT NULL DEFAULT 0;
